Update mariadb plugin
lando/backdrop pull request #47
Opened 2024-04-27 19:30 UTC by uberhacker

### Bare minimum self-checks

> [What do you think of a person who only does the bare minimum?](https://getyarn.io/yarn-clip/dcf80710-425e-478b-bde1-c107bd11e849)

- [x] I've updated this PR with the latest code from `main`
- [x] I've done a cursory QA pass of my code locally
- [x] I've ensured all automated status check and tests pass
- [x] I've [connected this PR to an issue](https://help.zenhub.com/support/solutions/articles/43000010350-connecting-pull-requests-to-github-issues)

### Pieces of flare

- [x] I've written a unit or functional test for my code
- [x] I've updated relevant documentation it my code changes it
- [x] I've updated this repo's README if my code changes it
- [x] I've updated this repo's CHANGELOG with my change unless its a trivial change (like updating a typo in the docs)

### Finally

- [x] I've [requested a review](https://help.github.com/en/articles/requesting-a-pull-request-review) with relevant people

If you have any issues or need help please join the `#contributors` channel in the [Lando slack](https://www.launchpass.com/devwithlando) and someone will gladly help you out!

You can also check out the [coder guide](https://docs.lando.dev/contrib/coder.html).

2024-04-27 20:02 UTC, xurizaemon requested changes
Not a maintainer, but I'd recommend to make separate PRs for the mariadb update and the text changes, rather than combining changes into one. 

Text cleanup is helpful but mixing changes in PRs can hide unexpected change.

Same thoughts as last review https://github.com/lando/acquia/pull/95 on including version number and release date in CHANGELOG.

2024-04-27 20:11 UTC, uberhacker commented on .github/workflows/release.yml
So many acronyms and so little time. :)  Yeah, exactly why we should spell it out.

2024-04-27 20:13 UTC, uberhacker commented on PRIVACY.md
What do you mean by "legal text"?  Just fixing a spelling error.

2024-04-27 21:31 UTC, uberhacker commented
> Not a maintainer, but I'd recommend to make separate PRs for the mariadb update and the text changes, rather than combining changes into one.
> 
> Text cleanup is helpful but mixing changes in PRs can hide unexpected change.
> 
> Same thoughts as last review [lando/acquia#95 (comment)](https://github.com/lando/acquia/pull/95#discussion_r1564381507) on including version number and release date in CHANGELOG.

So are you suggesting the version should be `1.3.1` instead of `1.4.0`? [#51[(https://github.com/lando/mariadb/issues/51) mentions to update the docs.  I figured a codespell check wouldn't hurt to clean up.

2024-04-28 05:20 UTC, xurizaemon commented on PRIVACY.md
I mean it doesn't look like regular English, but "legalese". We can see that if this is "just a spelling error", it's one propagated through many Lando plugins ([search for "softwares"](https://github.com/search?q=org%3Alando%20softwares&type=code) shows many results) and that file appears to be a legal document.

As a fellow contributor and maintainer of other projects, I recommend to propose changes "atomically", ie changing only one thing at a time. Mixing a version bump with changes to legal text can complicate review, or might have downstream effects if that "spelling mistake" actually affected something. I would guess not ... but it's so much easier to focus scope of a PR and be _certain_ there are no unexpected side-effects for the project.

If "softwares" really needs fixing, it would make more sense to fix that across the [dozens of places it appears in Lando plugins](https://github.com/search?q=org%3Alando%20softwares&type=code) in one go, rather than ad-hoc alongside other changes.

As noted: I'm not a maintainer here, so it's up to Lando team to make the call!

2024-04-28 05:25 UTC, xurizaemon commented
> So are you suggesting the version should be 1.3.1 instead of 1.4.0? https://github.com/lando/mariadb/issues/51 mentions to update the docs. I figured a codespell check wouldn't hurt to clean up.

More "I don't know, so I recommend to check what the correct next version and publication date will be before making that assertion" than "I think it should be different".

Comparing https://github.com/lando/drupal/blob/main/CHANGELOG.md I suspect your version change to 1.4.0 is the correct one. I would probably leave the date out of the CHANGELOG because I wouldn't want to guess at the release date. (For me it's easier to keep an "Unreleased" section at the top of the CHANGELOG, and let the maintainer make the updates when releases are cut, but that varies per project ... if Lando style is for the proposer to add a date, so be it!)

2024-04-28 05:40 UTC, uberhacker commented on PRIVACY.md
I see what you mean now.  This brings up another question.  Why are we making changes in dozens of places instead of change one and use anywhere?

2024-04-28 05:44 UTC, uberhacker commented on PRIVACY.md
More on the reason for the proposed change: https://thewordcounter.com/plural-of-software/

2024-04-28 15:56 UTC, xurizaemon commented on PRIVACY.md
This thread is now well outside the scope of "Update mariadb plugin".

I recommend moving changes unrelated to the subject of the PR to a separate change. IMO the changes in this PR which **do** belong here are those proposed to:

- .github/workflows/pr-backdrop-tests.yml
- CHANGELOG.md
- examples/backdrop-mariadb/.lando.yml
- examples/backdrop-mariadb/README.md
- examples/backdrop-mariadb/web/index.php
- examples/backdrop-mariadb/web/info.php
- package-lock.json
- package.json

Those changes look good to me, based on comparison with existing examples and other plugins.

It's great to tidy as you go - I respect the good scouting attitude! - but mixing changes introduces complications you don't need, and moving them to a separate PR is easy to do.

https://www.netlify.com/blog/2020/03/31/how-to-scope-down-prs/ may explain this better than I am managing to do?

2024-04-28 22:21 UTC, uberhacker commented on PRIVACY.md
@xurizaemon: Moved other changes to #49.  Appreciate your feedback.  This brings up another question.  How do we handle multiple pull requests in the same release?  Obviously, we don't want multiple entries in `CHANGELOG.md`.  Any suggestions @reynoldsalec?

2024-04-29 18:55 UTC, xurizaemon commented on PRIVACY.md
Nice. I'm happy with the changes here now, keen to see tests run which requires a manual action by Lando core team I think.

On the CHANGELOG, yeah I agree. Picking release numbers and dates is out of scope for a PR (that really only works for a maintainer who is cutting releases immediately). A format that works better for contribution is something like https://keepachangelog.com with changes landing in an "Unreleased" section, leaving release management for the maintainer later.

That's a discussion for a separate issue and not specific to this repo, IMO.

2024-04-29 18:56 UTC, xurizaemon approved these changes
LGTM, awaiting test run.

2024-04-29 19:47 UTC, uberhacker commented on PRIVACY.md
Agree this should be a maintainer responsibility.  Maybe the tagged release message can be appended to CHANGELOG.md as part of the process?  Typically a release message would include a summary line item for each commit/PR along with a diff of changes from the previous release.  [This looks interesting](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).

2024-04-29 19:59 UTC, xurizaemon commented on PRIVACY.md
I've opened https://github.com/lando/lando/issues/3710 for this, let's discuss there.

2024-04-30 18:00 UTC, reynoldsalec commented
@uberhacker I think the error on the mariadb test is from using the `mysql` binary...I guess we'd have to add `mariadb` as a tooling command (similar to how we add `mysql`: https://github.com/lando/backdrop/blob/main/utils/get-tooling-defaults.js#L45

2024-04-30 20:53 UTC, uberhacker commented
> @uberhacker I think the error on the mariadb test is from using the `mysql` binary...I guess we'd have to add `mariadb` as a tooling command (similar to how we add `mysql`: https://github.com/lando/backdrop/blob/main/utils/get-tooling-defaults.js#L45

This should be ready to go now @reynoldsalec.  All tests passed.

2024-05-01 19:31 UTC, reynoldsalec approved these changes

2024-05-01 19:32 UTC, merged